name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    ghCreateRelease: true
    ghReleaseAddChangeLog: true
    buildSteps:
      - script: yarn install --frozen-lockfile
        displayName: Install dependencies
      - script: yarn lint
        displayName: Static analysis
      - script: yarn package
        displayName: Compile extension